### PR TITLE
Rework corporate contact paragraph

### PR DESCRIPTION
**Pull request by jow-**
Signed-off-by: Jo-Philipp Wich jo@mein.io

### CODE REVIEW

**Comment by jow-** [comment]
Preview at http://lede-preview.mein.io/communication.html#corporate_contact

**Comment by bobafetthotmail** [comment]
"cooperate identity"? sounds like a typo. Also in the PR title.

**Comment by jow-** [comment]
Fixed.

**Comment by jow-** [comment]
Pulled into web.git: 0da6f8ddc86b1bee176b0a15cb1bf7e200d61d00

**Pull request closed without merging**
