### PR TITLE
Convert web to jekyll-asciidoc

### PR DESCRIPTION
**Pull request by azuwis**
Demo of the result https://azuwis.github.io/lede-web/

Use [jekyll-asciidoc-quickstart](https://github.com/asciidoctor/jekyll-asciidoc-quickstart) as a starting point, [jekyll-asciidoc](https://github.com/asciidoctor/jekyll-asciidoc/) as the static site generator.

### CODE REVIEW

**Comment by blogic** [comment]
looks pretty cool. i like it lets see what others have to say.  i;ll try this on a tablet and a mobile phone during the day,

nitpick would be that the logo seems a little small the rest looks better than the previous css

**Comment by jow-** [comment]
I like it very much, two little remarks from me:
- would be great to have a little more space between the upper left logo and the title right to it
- the word spacing seems to be quite narrow, maybe it can be slightly extended

**Comment by blogic** [comment]
small incompatibility between asciidoc and asciidoctor on the download page.  ~---~ does not get parsed properly.

**Comment by joanwa** [comment]
thumbs up!

**Comment by Noltari** [comment]
Awesome!
BTW, I agree with @jow- about the space between the logo and the title.
@blogic: looks good on my iPhone.

**Comment by blogic** [comment]
@Noltari thanks for testing

**Comment by azuwis** [comment]
Thanks for the feedback, I'll try to improve it later.
May take some time, I'm not a CSS guy :)

**Comment by blogic** [comment]
@azuwis looks good thanks ! i think with the a few minor tweaks, this will become the new css style

**Comment by Noltari** [comment]
@blogic @azuwis after deeper testing some wide tables aren't looking so good when there isn't enough screen on my iPhone, but I guess this is normal...

**Comment by jow-** [comment]
I suggest a CSS rule like that to prevent the menu from shifting too far right when there's a very wide screen:

```
.top-bar-section {
    max-width: 100rem !important;
}
```

**Comment by karlp** [comment]
- The links box dissappears to the bottom of the page when I split my screen in two vertically.  THis makes it very hard to have the documentation open with it's menu, and still have the work I need the docs open on the other half.  
- I think the top links are way to far to the right on a wide screen.  (minor)
- I find it very confusing to have the document tree and lists of links on the right.  If we yell at people for top posting, why on earth would we want right to left for a left to right language?

**Comment by jow-** [comment]
@karlp The disappearing link box is intentional and caused by media queries. I think this is a sensible solution to release horizontal space if the window becomes too narrow. Note that the link box pops to the bottom and utilizies 100% width there when the window width falls below a certain threshold.

The top links too far right issue should be addressed by the CSS rule I proposed above.

**Comment by karlp** [comment]
The menu that _remains_ on top is the less useful menu.  At least within the documentation tree, this might be different for the front page links to github and the downloads.  But within documentation, I want the links to the other documentation sections on top, not thrown to the bottom of an arbitrarily long page.

**Comment by karlp** [comment]
also, the header bar breaks into two rows on pages like https://azuwis.github.io/lede-web/docs/uci_dnsmasq.html on half screen.

**Comment by jow-** [comment]
@azuwis  The following code in `lede.css` will handle the broken-in-two-rows situation in a more graceful way:

```
@media only screen and (min-width: 40.063em) {
    .top-bar {
        height: auto;
        min-height: 2.8125rem;
    }  
}
```

**Comment by jow-** [comment]
@karlp - I agree, in the document tree case it shouldn't pop to the end, I did not check the documentation pages yet.

**Comment by jow-** [comment]
@azuwis - I think for the documentation pages it would make sense to put the document tree box to the left, then it would slide right under the main menu when the window is too narrow.

**Comment by pepe2k** [comment]
Awesome! Great job!

**Comment by jow-** [comment]
Pulled into web.git: https://git.lede-project.org/?p=web.git;a=commit;h=f7cdc186832ad94f1bafe1c929610a31da26da26

**Comment by blogic** [comment]
@azuwis thanks

**Comment by jow-** [comment]
@azuwis - thanks again for your great effort! Getting the ruby stack installed on the server was a little exercise in pain but the first generation cycle went through smoothly.

The new design is online now :)

**Pull request closed without merging**
