### PR TITLE
Update patch instructions and architecture discovery process.

### PR DESCRIPTION
**Pull request by marvinmarnold**
Signed-off-by: Marvin Arnold marvinmarnold@gmail.com

### CODE REVIEW

**Comment by jow-** [comment]
Pulled into web.git: 59eb847ca0a6774e335c9b18566fc0cd567f9970

**Comment by mkresin** [comment]
@marvinmarnold Am I right that 

> Section 1.1 of the https://www.kernel.org/doc/Documentation/SubmittingPatches

is a typo? To my reading Section 1.11 is about signing.

**Comment by marvinmarnold** [comment]
Thanks @mkresin you are correct. Please see https://github.com/lede-project/web/pull/38

**Comment by marvinmarnold** [comment]
Shoot, I did the commit through Github and ironically didn't sign-off. Let me revert.

**Pull request closed without merging**
