### PR TITLE
Added miscellaneous catch-all page for uncategorised documentation

### PR DESCRIPTION
**Pull request by Borromini**
As discussed with blogic this is a catch-all page to list uncategorised documentation, so people can consult it, and so we don't have overlap in pages being contributed. This addresses Issue #31.

Comments welcome; I think e.g. the development.txt and development_new_device.txt could be merged (or the former be renamed for clarity). Happy to revise.

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
> the development.txt and development_new_device.txt could be merged (or the former be renamed for clarity). Happy to revise.

I kept them separate for easier reading, and because both are stubs.

I wanted to avoid the effect there is on the Networking page, where lots of relatively different things (switch, basic networking, package-specific networking additional configurations) are bunched together with no obvious way to know where something you are looking for is (or requiring you to scroll the whole page for a long time to find it) or why they are in that particular order at all.

if they are each on their own document with a link on the left it's easy to see at a glance (and go to) any article.

Also, somewhat unrelated: I don't think indexing pages and keeping different things on the same page the way it is done now (they are divided per configuration file, and kept under the UCI configuration main page) is a logical way for documentation aimed at people that does not know where a particular setting is stored in beforehand (i mean ok, for networking is easy, but for others?)

**Comment by blogic** [comment]
@jow- - comments on this one ?

**Comment by jow-** [comment]
LGTM

**Comment by Borromini** [comment]
Thanks, I will adapt my pull request later today as per bobafetthotmail's remarks.

**Comment by Borromini** [comment]
I've removed the remark on a possible merge.

**Comment by lynxis** [comment]
The webpage is now a wiki. So this repo is deprecated.

**Pull request closed without merging**
